### ISSUE TITLE
Main page is misleading

### ISSUE THREAD

**Issue by jvoisin** [SecuRT/securt.github.io#2]
It would be super-great to a landing main page with every information needed to get what SECU'RT is, like:
- What is SECU'RT?
- When is it?
- Where?
- Why?
- Who?

**Comment by ghost** [comment]
Editing main page for it

**Comment by ghost** [comment]
done

**Comment by jvoisin** [comment]
It seems that you forgot to mention when/where/why/who ;)

**Comment by DePierre** [comment]
@dg3nce On top of that, I would have some remarks concerning the wording of the "Informations" paragraph.
- 3 times "organisé" in the first 3 sentences
- A link to the Université de Franche Compté?
- The hackerspace of Belfort has a name
- "Conférences et rencontres avec des professionels et acteurs de la sécurité IT vous sont proposé**e**s"
- "Venez vous mesurer face aux autres équipes" is not proper French. Whether it is "Venez faire face aux..." or "Venez vous mesurer aux..."

The paragraph is still confusing as @jvoisin pointed out, and misses many information.

**Comment by jvoisin** [comment]
@DePierre I tried to fix this in 3e6bd2e5275387c83d550197379c365fe361c06b
Care to review?

**Comment by DePierre** [comment]
@jvoisin @dg3nce How about something like this?

``` text
La Secu'RT est un événement autour de la sécurité informatique, organisée par des passionnés à l'intention des
intéressés. Elle est le fruit d'un travail collaboratif et bénévole entre le département Réseaux et Télécommunications de
l'Université de Franche-Comté et du Hackgyver, le hackerspace de Belfort, qui dure depuis trois années maintenant.

La Secu'RT vous attend le jeudi 10 mars 2016, à partir de 9 heures jusqu'à 19h, dans les locaux de l'université à
Montbéliard. Les plans d'accès vous sont fourni ci-dessous.

Au programme:
+ de 09h00 à 09h30, accueil des intéressés
+ de 09h30 à 12h30, conférences proposées par des professionnels et acteurs du monde de la sécurité informatique
+ de 12h30 à 13h00, pause déjeuner offerte par l'université
+ de 13h00 à 19h00, compétition de sécurité type CTF avec challenges de rétro-ingénierie, applications web vulnérables,
sécurité des réseaux et bien d'autres encores (ordinateurs requis !)

Venez apprendre, comprendre et rencontrer !
```

The schedule is made up but you get the idea. Feedback?

(_Update:_ Fixed some typos and specified that a laptop is required for the CTF)

**Comment by DePierre** [comment]
@vconnat In the new homepage:
- "ouvert à tous et à toutes" be a gentleman, the ladies first.
- "il se déroulera le jeudi 10 mars 2016", in present that works better like "Cette année, la SecuRT se déroule le jeudi 10 mars" (2016 is not needed).
- "N'oubliez pas d'ammener votre propre ordinateur." It looks very cheap whith such a big font. Maybe smaller? I mean it is not the most important information of the event. I would put "Venez apprendre, comprendre et rencontrer!" bigger instead personally.

Please update!
