### ISSUE TITLE
Contact email address hosted by the Universty

### ISSUE THREAD

**Issue by DePierre** [SecuRT/securt.github.io#3]
@dg3nce I think it would be better for the image of the event to have a dedicated email address hosted by the université de Franche-Compté.

Something like "securt@univ-fc.fr" or whatever is the domain name of the University.

Do you think it would be possible to start the processus of creating such email address?

**Comment by ghost** [comment]
We requested the creation of the email (mail server forbidden due to obvious security issues), now waiting for a authorization from the communication service. But it will be a temporary email which will be destroyed next September.
